### PR TITLE
update to 2017.10

### PR DESCRIPTION
**Pull request by rvalieris**

### CODE REVIEW

**Comment by rvalieris** [comment]
>target-feedstock

oops, apparently conda smithy uses the name of the directory....

edit: stealthy updated the commit

**Comment by jdblischak** [comment]
Thanks for the PR, @rvalieris!

Could you please add the GPL-3 license?

```
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]
```

And could you please add daler and yourself to the list of recipe-maintainers?

**Comment by rvalieris** [comment]
added !

**Review by jdblischak — APPROVED** [review]

**Comment by jdblischak** [comment]
@rvalieris Please ping me when the CI builds finish so I can merge

**Comment by rvalieris** [comment]
ping !

**Pull request merged**
